/**
 * Complete list of all Vanderbilt subject codes
 */
export const SUBJECT_CODES = [
  'AADS', 'ANTH', 'ARA', 'ARAM', 'ARTS', 'ASAM', 'ASIA', 'ASL', 'ASTR',
  'BASS', 'BCB', 'BME', 'BNJO', 'BRQ', 'BSCI', 'BSSN', 'BUS', 'BUSA',
  'CAL', 'CAR', 'CE', 'CHBE', 'CHEB', 'CHEM', 'CHIN', 'CHRK', 'CLAR',
  'CLAS', 'CLLO', 'CMA', 'CMST', 'COMP', 'CORE', 'CREO', 'CS', 'CSET',
  'CTLN', 'DF', 'DHUM', 'DRUM', 'DS', 'ECE', 'ECON', 'EDUC', 'EES',
  'ENED', 'ENGL', 'ENGM', 'ENVE', 'ENVS', 'ES', 'EUPH', 'EUS', 'FDDL',
  'FLED', 'FLUT', 'FNTE', 'FNTM', 'FREN', 'GER', 'GRK', 'GSS', 'GTR',
  'HARP', 'HART', 'HEBR', 'HIST', 'HMED', 'HNUR', 'HOD', 'HODC', 'HODE',
  'HODH', 'HODI', 'HODL', 'HONS', 'HORN', 'HRPS', 'HUM', 'IDIS', 'IMM',
  'INDS', 'ITA', 'JAPN', 'JAZZ', 'JS', 'KICH', 'KOR', 'LACX', 'LAS',
  'LAT', 'LATS', 'MALA', 'MATH', 'MCON', 'ME', 'MENT', 'MHS', 'MNDL',
  'MPED', 'MREP', 'MS', 'MS-PC', 'MSE', 'MTEC', 'MTED', 'MUED', 'MUKH',
  'MUSC', 'MUSE', 'MUSL', 'MUSO', 'MUTH', 'MWEL', 'NANO', 'NEXT', 'NS',
  'NS-PC', 'NSC', 'OBOE', 'ORGN', 'PBDY', 'PERC', 'PERS', 'PHIL', 'PHYS',
  'PIAN', 'PORT', 'PPS', 'PSCH', 'PSCI', 'PSY', 'PSY-PC', 'RLST', 'RPW',
  'RUSS', 'SAX', 'SC', 'SCED', 'SNSK', 'SOC', 'SPAN', 'SPED', 'SPEDH',
  'SPEDS', 'SPEDV', 'SSED', 'STPN', 'SWAH', 'TBTN', 'THTR', 'TROM',
  'TRPT', 'TUBA', 'TURK', 'ULAW', 'UNIV', 'VLA', 'VLN', 'VOIC', 'VV',
] as const;


/**
 * Mapping from subject names to subject codes
 */
export const SUBJECT_NAME_TO_CODE: Record<string, string> = {
  'african american and diaspora studies': 'AADS',
  'american sign language': 'ASL',
  'anthropology': 'ANTH',
  'arabic': 'ARA',
  'aramic and syriac': 'ARAM',
  'art studio': 'ARTS',
  'arts and science college core': 'CORE',
  'asian studies': 'ASIA',
  'asian-american studies': 'ASAM',
  'astronomy': 'ASTR',
  'baroque perform instruction in string instruments': 'BRQ',
  'biochemistry and chemical biology': 'BCB',
  'biological sciences': 'BSCI',
  'biomedical engineering': 'BME',
  'business': 'BUS',
  'business - arts and science': 'BUSA',
  'career development': 'CAR',
  'catalan': 'CTLN',
  'chemical and biomolecular engineering': 'CHBE',
  'chemistry': 'CHEM',
  'cherokee': 'CHRK',
  'chinese': 'CHIN',
  'cinema and media arts': 'CMA',
  'civil engineering': 'CE',
  'classical hebrew': 'CHEB',
  'classics': 'CLAS',
  'communication of science and technology': 'CSET',
  'communication studies': 'CMST',
  'computer science': 'CS',
  'conducting': 'MCON',
  'culture, advocacy, and leadership': 'CAL',
  'data science': 'DS',
  'digital fabrication': 'DF',
  'digital humanities': 'DHUM',
  'earth and environmental sciences': 'EES',
  'economics': 'ECON',
  'education': 'EDUC',
  'electrical and computer engineering': 'ECE',
  'engineering management': 'ENGM',
  'engineering science': 'ES',
  'english': 'ENGL',
  'english education': 'ENED',
  'ensembles': 'MUSE',
  'environmental and sustainability studies': 'ENVS',
  'environmental engineering': 'ENVE',
  'european studies': 'EUS',
  'financial management': 'FNTM',
  'foreign language education': 'FLED',
  'foreign programs-engineering': 'FNTE',
  'french': 'FREN',
  'gender and sexuality studies': 'GSS',
  'german': 'GER',
  'greek': 'GRK',
  'haitian creole language': 'CREO',
  'hebrew': 'HEBR',
  'hindi urdu language instruction': 'HNUR',
  'history': 'HIST',
  'history of art': 'HART',
  'honors': 'HONS',
  'human and organizational development': 'HOD',
  'human and organizational development: community leadership and development': 'HODC',
  'human and organizational development: education policy': 'HODE',
  'human and organizational development: health and human services': 'HODH',
  'human and organizational development: international leadership and policy': 'HODI',
  'human and organizational development: leadership and organizational effectiveness': 'HODL',
  'humanities': 'HUM',
  'humanities education-pc': 'HMED',
  'immersion vanderbilt': 'IMM',
  'interdisciplinary studies': 'INDS',
  'interdisciplinary-med': 'IDIS',
  'italian': 'ITA',
  'japanese': 'JAPN',
  'jazz and global music': 'JAZZ',
  'jewish studies': 'JS',
  "k'iche' - mayan language": 'KICH',
  'keyboard harmony': 'MUKH',
  'korean': 'KOR',
  'latin': 'LAT',
  'latin american caribbean studies': 'LACX',
  'latin american studies': 'LAS',
  'latino and latina studies': 'LATS',
  'malagasy': 'MALA',
  'material science and engineering': 'MSE',
  'math education': 'MTED',
  'mathematics': 'MATH',
  'mechanical engineering': 'ME',
  'medicine, health, and society': 'MHS',
  'military science': 'MS',
  'military science-pc': 'MS-PC',
  'minor in legal studies': 'ULAW',
  'music business/entrepreneurship': 'MENT',
  'music composition': 'COMP',
  'music pedagogy': 'MPED',
  'music repertoire/literature': 'MREP',
  'music teacher education': 'MUED',
  'music technology': 'MTEC',
  'music theory': 'MUTH',
  'musicianship': 'MUSC',
  'musicology/ethnomusicology': 'MUSL',
  "musicians' wellness": 'MWEL',
  'nanoscience and nanotechnology': 'NANO',
  'naval science': 'NS',
  'naval science-pc': 'NS-PC',
  'neuroscience': 'NSC',
  'next steps': 'NEXT',
  'other music courses': 'MUSO',
  'peabody college': 'PBDY',
  'peabody honors scholars': 'PSCH',
  'performance instruction: banjo': 'BNJO',
  'performance instruction: bass': 'BASS',
  'performance instruction: bassoon': 'BSSN',
  'performance instruction: cello': 'CLLO',
  'performance instruction: clarinet': 'CLAR',
  'performance instruction: drumset': 'DRUM',
  'performance instruction: euphonium': 'EUPH',
  'performance instruction: fiddle': 'FDDL',
  'performance instruction: flute': 'FLUT',
  'performance instruction: guitar classical': 'GTR',
  'performance instruction: harp': 'HARP',
  'performance instruction: harpischored': 'HRPS',
  'performance instruction: horn': 'HORN',
  'performance instruction: mandolin': 'MNDL',
  'performance instruction: oboe': 'OBOE',
  'performance instruction: organ': 'ORGN',
  'performance instruction: percussion': 'PERC',
  'performance instruction: piano': 'PIAN',
  'performance instruction: saxophone': 'SAX',
  'performance instruction: steel pan': 'STPN',
  'performance instruction: trombone': 'TROM',
  'performance instruction: trumpet': 'TRPT',
  'performance instruction: tuba': 'TUBA',
  'performance instruction: viola': 'VLA',
  'performance instruction: violin': 'VLN',
  'performance instruction: voice': 'VOIC',
  'persian': 'PERS',
  'philosophy': 'PHIL',
  'physics': 'PHYS',
  'political science': 'PSCI',
  'portuguese': 'PORT',
  'psychology': 'PSY',
  'psychology-pc': 'PSY-PC',
  'public policy studies': 'PPS',
  'religious studies': 'RLST',
  'robert penn warren center': 'RPW',
  'russian': 'RUSS',
  'sanskrit': 'SNSK',
  'science education': 'SCED',
  'scientific computing': 'SC',
  'social studies education': 'SSED',
  'sociology': 'SOC',
  'spanish': 'SPAN',
  'special education': 'SPED',
  'special education multiple and severe disabilities': 'SPEDS',
  'special education: high incidence': 'SPEDH',
  'special education: visual impairments': 'SPEDV',
  'swahili language': 'SWAH',
  'theatre': 'THTR',
  'tibetan language': 'TBTN',
  'turkish language': 'TURK',
  'university courses': 'UNIV',
  'vanderbilt visions': 'VV',
};

/**
 * Check if a string is a valid subject code
 */
export function isValidSubjectCode(code: string): boolean {
  return SUBJECT_CODES.includes(code.toUpperCase() as any);
}

/**
 * Get subject code from subject name (case-insensitive)
 * Returns undefined if no match found
 */
export function getSubjectCodeByName(name: string): string | undefined {
  return SUBJECT_NAME_TO_CODE[name.toLowerCase()];
}

/**
 * Get all subject codes that start with a given prefix
 * Case-insensitive prefix matching
 */
export function getSubjectsByPrefix(prefix: string): string[] {
  const upperPrefix = prefix.toUpperCase();
  return SUBJECT_CODES.filter((code) => code.startsWith(upperPrefix));
}
